/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/rishubhp/vaibhav/meesho-project/training_scripts/infer_safe_singleobject.py", line 402, in <module>
[rank2]:     pipeline = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1").to(accelerator.device)   
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 670, in to
[rank2]:     module.to(torch_device, torch_dtype)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1682, in to
[rank2]:     return super().to(*args, **kwargs)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1174, in to
[rank2]:     return self._apply(convert)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank2]:     module._apply(fn)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank2]:     module._apply(fn)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank2]:     module._apply(fn)
[rank2]:   [Previous line repeated 3 more times]
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 805, in _apply
[rank2]:     param_applied = fn(param)
[rank2]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in convert
[rank2]:     return t.to(
[rank2]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 2 has a total capacity of 23.67 GiB of which 11.56 MiB is free. Process 1282142 has 22.04 GiB memory in use. Including non-PyTorch memory, this process has 1.61 GiB memory in use. Of the allocated memory 1.38 GiB is allocated by PyTorch, and 31.88 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
ckpt_path = '../ckpts/multiobject/__freezeapp_large/training_state_110000.pth'
lora_path = '../ckpts/multiobject/__freezeapp_large/lora_weight_110000.safetensors'
loading stable diffusion checkpoint...
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/rishubhp/vaibhav/meesho-project/training_scripts/infer_safe_singleobject.py", line 402, in <module>
[rank1]:     pipeline = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1").to(accelerator.device)   
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 670, in to
[rank1]:     module.to(torch_device, torch_dtype)
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1174, in to
[rank1]:     return self._apply(convert)
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank1]:     module._apply(fn)
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank1]:     module._apply(fn)
[rank1]:   [Previous line repeated 5 more times]
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 805, in _apply
[rank1]:     param_applied = fn(param)
[rank1]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in convert
[rank1]:     return t.to(
[rank1]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 1 has a total capacity of 23.67 GiB of which 19.56 MiB is free. Process 1282141 has 22.90 GiB memory in use. Including non-PyTorch memory, this process has 758.00 MiB memory in use. Of the allocated memory 540.20 MiB is allocated by PyTorch, and 15.80 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/rishubhp/vaibhav/meesho-project/training_scripts/infer_safe_singleobject.py", line 402, in <module>
[rank3]:     pipeline = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1").to(accelerator.device)   
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py", line 670, in to
[rank3]:     module.to(torch_device, torch_dtype)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/transformers/modeling_utils.py", line 1682, in to
[rank3]:     return super().to(*args, **kwargs)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1174, in to
[rank3]:     return self._apply(convert)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
[rank3]:     module._apply(fn)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 805, in _apply
[rank3]:     param_applied = fn(param)
[rank3]:   File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in convert
[rank3]:     return t.to(
[rank3]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 194.00 MiB. GPU 3 has a total capacity of 23.67 GiB of which 91.56 MiB is free. Process 1282143 has 23.37 GiB memory in use. Including non-PyTorch memory, this process has 202.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
W0815 23:05:00.171595 140565803341632 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1363189 closing signal SIGTERM
E0815 23:05:00.386889 140565803341632 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 1363190) of binary: /home/rishubhp/miniconda3/envs/contwords/bin/python
Traceback (most recent call last):
  File "/home/rishubhp/miniconda3/envs/contwords/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/accelerate/commands/launch.py", line 914, in launch_command
    multi_gpu_launcher(args)
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/accelerate/commands/launch.py", line 603, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/rishubhp/miniconda3/envs/contwords/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
infer_safe_singleobject.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-08-15_23:05:00
  host      : cn3.cds.iisc.in
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 1363191)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-08-15_23:05:00
  host      : cn3.cds.iisc.in
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1363192)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-08-15_23:05:00
  host      : cn3.cds.iisc.in
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1363190)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
